#******************************* BombCrypto Bot *********************************#
#â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€#
#â”€â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ”€â”€â”€â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ”€â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ”€â”€â”€â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ”€â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ”€#
#â”€â–ˆâ–ˆâ–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–ˆâ–ˆâ”€â”€â”€â–ˆâ–ˆâ–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–ˆâ–ˆâ”€â–ˆâ–ˆâ–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–ˆâ–ˆâ”€â”€â”€â–ˆâ–ˆâ–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–ˆâ–ˆâ”€â–ˆâ–ˆâ–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–ˆâ–ˆâ”€#
#â”€â–ˆâ–ˆâ–‘â–‘â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–‘â–‘â–ˆâ–ˆâ”€â”€â”€â–ˆâ–ˆâ–‘â–‘â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ”€â–ˆâ–ˆâ–‘â–‘â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–‘â–‘â–ˆâ–ˆâ”€â”€â”€â–ˆâ–ˆâ–‘â–‘â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–‘â–‘â–ˆâ–ˆâ”€â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–‘â–‘â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ”€#
#â”€â–ˆâ–ˆâ–‘â–‘â–ˆâ–ˆâ”€â”€â–ˆâ–ˆâ–‘â–‘â–ˆâ–ˆâ”€â”€â”€â–ˆâ–ˆâ–‘â–‘â–ˆâ–ˆâ”€â”€â”€â”€â”€â”€â”€â”€â”€â–ˆâ–ˆâ–‘â–‘â–ˆâ–ˆâ”€â”€â–ˆâ–ˆâ–‘â–‘â–ˆâ–ˆâ”€â”€â”€â–ˆâ–ˆâ–‘â–‘â–ˆâ–ˆâ”€â”€â–ˆâ–ˆâ–‘â–‘â–ˆâ–ˆâ”€â”€â”€â”€â”€â–ˆâ–ˆâ–‘â–‘â–ˆâ–ˆâ”€â”€â”€â”€â”€#
#â”€â–ˆâ–ˆâ–‘â–‘â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–‘â–‘â–ˆâ–ˆâ–ˆâ–ˆâ”€â–ˆâ–ˆâ–‘â–‘â–ˆâ–ˆâ”€â”€â”€â”€â”€â”€â”€â”€â”€â–ˆâ–ˆâ–‘â–‘â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–‘â–‘â–ˆâ–ˆâ–ˆâ–ˆâ”€â–ˆâ–ˆâ–‘â–‘â–ˆâ–ˆâ”€â”€â–ˆâ–ˆâ–‘â–‘â–ˆâ–ˆâ”€â”€â”€â”€â”€â–ˆâ–ˆâ–‘â–‘â–ˆâ–ˆâ”€â”€â”€â”€â”€#
#â”€â–ˆâ–ˆâ–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–ˆâ–ˆâ”€â–ˆâ–ˆâ–‘â–‘â–ˆâ–ˆâ”€â”€â”€â”€â”€â”€â”€â”€â”€â–ˆâ–ˆâ–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–ˆâ–ˆâ”€â–ˆâ–ˆâ–‘â–‘â–ˆâ–ˆâ”€â”€â–ˆâ–ˆâ–‘â–‘â–ˆâ–ˆâ”€â”€â”€â”€â”€â–ˆâ–ˆâ–‘â–‘â–ˆâ–ˆâ”€â”€â”€â”€â”€#
#â”€â–ˆâ–ˆâ–‘â–‘â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–‘â–‘â–ˆâ–ˆâ”€â–ˆâ–ˆâ–‘â–‘â–ˆâ–ˆâ”€â”€â”€â”€â”€â”€â”€â”€â”€â–ˆâ–ˆâ–‘â–‘â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–‘â–‘â–ˆâ–ˆâ”€â–ˆâ–ˆâ–‘â–‘â–ˆâ–ˆâ”€â”€â–ˆâ–ˆâ–‘â–‘â–ˆâ–ˆâ”€â”€â”€â”€â”€â–ˆâ–ˆâ–‘â–‘â–ˆâ–ˆâ”€â”€â”€â”€â”€#
#â”€â–ˆâ–ˆâ–‘â–‘â–ˆâ–ˆâ”€â”€â”€â”€â–ˆâ–ˆâ–‘â–‘â–ˆâ–ˆâ”€â–ˆâ–ˆâ–‘â–‘â–ˆâ–ˆâ”€â”€â”€â”€â”€â”€â”€â”€â”€â–ˆâ–ˆâ–‘â–‘â–ˆâ–ˆâ”€â”€â”€â”€â–ˆâ–ˆâ–‘â–‘â–ˆâ–ˆâ”€â–ˆâ–ˆâ–‘â–‘â–ˆâ–ˆâ”€â”€â–ˆâ–ˆâ–‘â–‘â–ˆâ–ˆâ”€â”€â”€â”€â”€â–ˆâ–ˆâ–‘â–‘â–ˆâ–ˆâ”€â”€â”€â”€â”€#
#â”€â–ˆâ–ˆâ–‘â–‘â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–‘â–‘â–ˆâ–ˆâ”€â–ˆâ–ˆâ–‘â–‘â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ”€â–ˆâ–ˆâ–‘â–‘â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–‘â–‘â–ˆâ–ˆâ”€â–ˆâ–ˆâ–‘â–‘â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–‘â–‘â–ˆâ–ˆâ”€â”€â”€â”€â”€â–ˆâ–ˆâ–‘â–‘â–ˆâ–ˆâ”€â”€â”€â”€â”€#
#â”€â–ˆâ–ˆâ–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–ˆâ–ˆâ”€â–ˆâ–ˆâ–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–ˆâ–ˆâ”€â–ˆâ–ˆâ–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–ˆâ–ˆâ”€â–ˆâ–ˆâ–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–ˆâ–ˆâ”€â”€â”€â”€â”€â–ˆâ–ˆâ–‘â–‘â–ˆâ–ˆâ”€â”€â”€â”€â”€#
#â”€â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ”€â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ”€â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ”€â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ”€â”€â”€â”€â”€â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ”€â”€â”€â”€â”€#
#â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€#
#********************************************************************************#
#********************* Please consider buying me a coffee ğŸ˜ ********************#
#********************************************************************************#
#******** BUSD/BCOIN (BEP20): 0x8c38512beca8b0b06bf4e85f67ee64a7dcdaa11a ********#
#********************************************************************************#

#****************************TELEGRAM CONFIG (OPTIONAL)**************************#
#                                                 ..
#                                            ..:::::
#                                       ..::::..::::
#                                 ...::::::. ..::::.
#                            ...:::::::..  .:::::::
#                        .:::::::::::    .::::::::.
#                         ...::::..    :::::::::::
#                                    .::::::::::::
#                                   .:::::::::::::
#                                  ::::::::::::::
#                                  ::.   .:::::-.
#                                  .        .:-:

# [en] Start a Telegram conversation with the @btsherald_bot and type /id to get your_chat_id.
# [pt_br] Inicie uma conversa no Telegram com @btsherald_bot e digite /id para pegar o your_chat_id.

# [en] Start a Telegram conversation with @botfather and type /newbot to get your_telegram_bot_token.
# [pt_br] Inicie uma conversa no Telegram com @botfather e digite /newbot para pegar o your_telegram_bot_token.

telegram_enable: false
telegram_chat_id: ["YOUR_CHAT_ID", "YOUR_CHAT_ID2(optional)"]
telegram_bot_token: "YOUR_TELEGRAM_BOT_TOKEN"
enable_coin_report: false
enable_map_report: false
format_of_images: "jpg"



























































































































































































































































# [en_US] PLEASE DON'T CHANGE
# [pt_BR] POR FAVOR NÃƒO ALTERE
version: "1.0.6"
